esphome:
  name: taaraesp-sht21
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp12e

logger:

api:

wifi:
  ssid: 
  password:

i2c:
  sda: 5
  scl: 4

sensor:
  - platform: htu21d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

deep_sleep:
  run_duration: 20s
  sleep_duration: 5min
